version: '2'
services:
  time-server:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic
      lagoon.service.usecomposeports: true
    ports:
      - "8080:8080" 